### ISSUE TITLE
Preprocessor can't handle CRLF files

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [davidgiven/ack#117] opened 2018-09-01 19:47 UTC
If I try to compile this:

```
#include <stdlib.h>
#include <stdio.h>

int main(int argc, const char *argv[])
{
        printf("Hello world!\n");

        return 0;
}
```
I get a bad include syntax error
"hello.c", line 2: bad include syntax
"hello.c", line 3: bad include syntax

**Comment by davidgiven** [comment] 2018-09-02 08:55
Yes, I can confirm this --- CRLF files confuse the preprocessor. This totally needs fixing.

**Comment by Fabrizio-Caruso** [comment] 2018-09-02 08:57
Thanks!

**Comment by davidgiven** [comment] 2018-09-02 09:13
So the #include issue was trivial --- \r wasn't being considered as whitespace, so this:

    #include <stdlib.h>CRLF

...was being parsed as:

    #include <stdlib.h>BOGUSCHAR

However, there's a more subtle problem in that line continuations are broken:

    #define FOO \

becomes:

    #define FOO \WHITESPACE

This means that line continuations never work in CRLF files, because they're never the last character in the line.

**Comment by davidgiven** [comment] 2018-09-02 09:30
That should be fixed now.

**Closed as completed** 2018-09-02 09:30 UTC
