### ISSUE TITLE
can't compile hilo.b for linux68k

### ISSUE THREAD

**Issue by kernigh** [davidgiven/ack#36] opened 2017-01-13 19:34 UTC
I'm running OpenBSD 6.0 for amd64. The build of git fd83b09 fails:

```
[11/754] ACKDIR=/home/kernigh/park/ack...xamples/hilo_b_linux68k/platstamp -O6 
FAILED: /home/kernigh/park/ack-build/obj/examples/hilo_b_linux68k/main/hilo/hilo.o 
ACKDIR=/home/kernigh/park/ack-build/staging /home/kernigh/park/ack-build/staging/bin/ack -mlinux68k -c -o /home/kernigh/park/ack-build/obj/examples/hilo_b_linux68k/main/hilo/hilo.o examples/hilo.b -I/home/kernigh/park/ack-build/obj/examples/hilo_b_linux68k/platstamp -O6 
/home/kernigh/park/ack-build/staging/bin/ack: warning, No definition for ABC_F
"Ack_167bdf.s", line 359: syntax error
[13/754] ACKDIR=/home/kernigh/park/ack.../cem/libcc.ansi/string/strpbrk.c  -O6 
ninja: build stopped: subcommand failed.
gmake: *** [Makefile:82: +ack] Error 1
```

I can reproduce it with the partly-built ack:

```
$ cd examples
$ ack -mlinux68k -c.o hilo.b -O6 
ack: warning, No definition for ABC_F
"Ack_7426f.s", line 359: syntax error
```

By using `-c.s`, I can generate the assembly code. Line 359 is the `$Id$ 1f` in

```
move.l #78,d1
move.l (sp)+,d2
cmp.l d1,d0
$Id$ 1f
bset #0,d2
1:
tst.l d2
beq I6_2
```

It seems that something goes wrong inside ncg for linux68k, so it outputs `$Id$` when it should output a branch instruction.

**Comment by davidgiven** [comment] 2017-01-15 22:24
Hmm, that's very interesting; that doesn't happen on Linux, producing this code:

    move.l #78,d1
    move.l (sp)+,d2
    cmp.l d1,d0
    bne 1f
    bset #0,d2
    1:
    tst.l d2
    beq I6_2

So that's exactly the same as yours, except with the right branch instruction. However, I can easily reproduce this on my 32-bit OpenBSD machine.

The only interesting thing I can spot is that the RCS id field at the top of the m68k's table is misspelt ('rscid'). But that shouldn't make any difference... I'll investigate.

**Comment by davidgiven** [comment] 2017-01-16 22:20
Fixed (along with a few others).

It was a buffer overrun causing stack corruption. I assume it was showing up on OpenBSD because of the different compiler version.

...I believe the original bug got checked in in 1985.

**Closed as completed by davidgiven** 2017-01-16 22:20 UTC

**Comment by kernigh** [comment] 2017-01-16 23:01
Thanks for finding and fixing it.

Commit fa5675d ("Run through clang-format.") has, in my opinion, made a mess of codegen() in mach/proto/ncg/codegen.c. A few comments got indented wrong, and several lines no longer fit in my 80-wide terminal. The real problem is that codegen() has far too much code for one function; no format tool can fix it.
